"""`just blueprints`: 20-groups.yaml generated from the dataset, and `--check` against it (AC-9)."""

from pathlib import Path

import pytest
import yaml

from tessaro_dataset import Dataset
from tessaro_dataset.exports.authentik import export_authentik
from tessaro_seed import blueprints

REPO_ROOT = Path(__file__).resolve().parents[3]


class _Tagged(yaml.SafeLoader):
    """Reads Authentik's custom tags (`!KeyOf seed-role`) as plain `[tag, value]` pairs."""


_Tagged.add_multi_constructor(
    "!",
    lambda loader, tag, node: [tag, loader.construct_scalar(node)],
)


def parsed(text: str) -> dict[str, object]:
    loaded = yaml.load(text, Loader=_Tagged)  # noqa: S506 - SafeLoader subclass with one tag rule
    assert isinstance(loaded, dict)
    return loaded


def test_every_dataset_group_is_declared_with_elevated(dataset: Dataset) -> None:
    doc = parsed(blueprints.render_groups(dataset))
    entries = doc["entries"]
    assert isinstance(entries, list)
    groups = {e["identifiers"]["name"]: e for e in entries if e["model"] == "authentik_core.group"}
    expected = export_authentik(dataset, include_demo_inputs=True).groups
    assert set(groups) == {g.name for g in expected}
    for group in expected:
        assert groups[group.name]["attrs"] == {"attributes": {"elevated": group.elevated}}


def test_the_seed_role_may_join_and_leave_every_dataset_group(dataset: Dataset) -> None:
    entries = parsed(blueprints.render_groups(dataset))["entries"]
    assert isinstance(entries, list)
    role = next(e for e in entries if e["model"] == "authentik_rbac.role")
    assert role == {
        "model": "authentik_rbac.role",
        "id": "seed-role",
        "state": "created",
        "identifiers": {"name": "tessaro-seed"},
    }
    for entry in (e for e in entries if e["model"] == "authentik_core.group"):
        assert entry["permissions"] == [
            {"permission": "authentik_core.add_user_to_group", "role": ["KeyOf", "seed-role"]},
            {"permission": "authentik_core.remove_user_from_group", "role": ["KeyOf", "seed-role"]},
        ]


def test_admin_groups_are_never_in_the_file(dataset: Dataset) -> None:
    text = blueprints.render_groups(dataset)
    assert "authentik Admins" not in text
    assert "svc-" not in text


def test_the_output_is_deterministic(dataset: Dataset) -> None:
    assert blueprints.render_groups(dataset) == blueprints.render_groups(dataset)


def test_main_writes_then_check_passes(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    out = tmp_path / "20-groups.yaml"
    args = ["--root", str(REPO_ROOT), "--out", str(out)]
    assert blueprints.main(args) == 0
    assert out.read_text().startswith("# Generated by `just blueprints`")
    assert blueprints.main([*args, "--check"]) == 0
    assert "up to date" in capsys.readouterr().out


def test_check_fails_when_the_file_is_stale(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    out = tmp_path / "20-groups.yaml"
    out.write_text("stale\n")
    assert blueprints.main(["--root", str(REPO_ROOT), "--out", str(out), "--check"]) == 1
    assert "just blueprints" in capsys.readouterr().err


def test_check_fails_when_the_file_is_missing(tmp_path: Path) -> None:
    out = tmp_path / "20-groups.yaml"
    assert blueprints.main(["--root", str(REPO_ROOT), "--out", str(out), "--check"]) == 1


def test_a_broken_dataset_exits_1(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    assert blueprints.main(["--root", str(tmp_path), "--out", str(tmp_path / "x.yaml")]) == 1
    assert "dataset" in capsys.readouterr().err


def test_the_committed_file_is_current() -> None:
    """The same check `just check` runs, so a dataset change without `just blueprints` fails CI."""
    assert blueprints.main(["--root", str(REPO_ROOT), "--check"]) == 0
