apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tessaro.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tessaro.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ include "tessaro.name" . | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
