apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tessaro.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tessaro.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
