---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netpol-proof
  namespace: tessaro-netpol-proof
spec:
  encryptedData:
    PROOF_VALUE: AgArworoYcqkJrZRjct+6OPQUuRIYEbTZIVdh6IDIiBDl4dbocb4TBKWxo97b1i+0ovu4MXVNHmd8oyWJEFIE5NBWkBof63BCQrISUwf5kRsa0qjicCCbzDcNK4+2vzuPuuLv9Q2nYkOTmhh5MXZd8iRK8LQslTDyl+tQ1as4Sl85+OsGx9NqQGlZ/yYu1PBVHvMhahy+/U4gieqg98t/nZ0jIdYbay9Puw9z04LClML5UD5hBGCr6v/IRgAMI9nQLAKLrkLPcML+S5Ii6GuT82T78i00It4GFSReu2CWV2s8SCy/bF8PDC8nRJ4UcVB3fxiShWnEi1QJ+NgdSBNYi6JAXlYove3oATNY1xQhNpGrDD3EFda7OU+crHE1yZ38flHzVWek4VfFU/uaBu//d2zw55yAJHe+UNiRHvDoHP7gf1WSImL/UEM5+ohUYCGoHwtXsgHahyfmth9QI7Fwk7n3joKA+FZ63D/2Mfga9SvjuJ8JeMzv9KcUckM9WjImU/rzaxVIqZhIs6VVCQqbzLdMsbpd1gcPgYtVlDj6aB4pWU5jCXy4AIFNUCO0M6qUCjZ0llc6UthqAvZMvZloBYOIewdSuGMRN52Mnct8oPReyvypweSPayVIOvMpDE+W4c/PYtzubb4Dyv8vXdWRdF4WyfJfmwPfNpHLdjc3HMQksr2B1nKawyIfQJwsGgW+nklngjwFyh1e+xKyvu8ASvKieX/
  template:
    metadata:
      name: netpol-proof
      namespace: tessaro-netpol-proof
    type: Opaque
