"""`just blueprints`: write Authentik's `20-groups.yaml` from the dataset (spec 0008 AC-9).

Every group the dataset can give anyone (demo input joiners included, so a joiner's groups exist
before the workflow needs them), each with `attributes.elevated`, and the seed role's object
permissions to add and remove members of exactly these groups. `--check` compares instead of
writing, so `just check` fails when the dataset changed and the file did not.
"""

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from tessaro_dataset import Dataset, DatasetError, load_dataset
from tessaro_dataset.exports.authentik import export_authentik
from tessaro_dataset.loader import DatasetPaths

GROUPS_FILE = Path("deploy/platform/authentik/manifests/blueprints/20-groups.yaml")
SEED_ROLE = "tessaro-seed"

HEADER = """\
# Generated by `just blueprints` from the dataset (spec 0008 AC-9); do not edit by hand.
# Every dataset group with `attributes.elevated`, and the seed role's permission to add and remove
# members of exactly these groups. `just check` fails when this file is stale.
version: 1
metadata:
  name: Tessaro - dataset groups
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  # Declared here too (30-seed.yaml sets its permissions), so file order never matters.
  - model: authentik_rbac.role
    id: seed-role
    state: created
    identifiers:
      name: {role}
"""

GROUP = """\
  - model: authentik_core.group
    identifiers:
      name: {name}
    attrs:
      attributes:
        elevated: {elevated}
    permissions:
      - permission: add_user_to_group
        role: !KeyOf seed-role
      - permission: remove_user_from_group
        role: !KeyOf seed-role
"""


def render_groups(dataset: Dataset) -> str:
    """The full text of `20-groups.yaml`, groups sorted by name."""
    groups = export_authentik(dataset, include_demo_inputs=True).groups
    body = "".join(
        GROUP.format(name=g.name, elevated=str(g.elevated).lower())
        for g in sorted(groups, key=lambda g: g.name)
    )
    return HEADER.format(role=SEED_ROLE) + body


def main(argv: Sequence[str] | None = None) -> int:
    """Write (or with ``--check`` compare) the groups blueprint; exit 1 when stale or broken."""
    parser = argparse.ArgumentParser(prog="tessaro-seed blueprints", description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="repo root")
    parser.add_argument("--out", type=Path, help=f"default <root>/{GROUPS_FILE}")
    parser.add_argument("--check", action="store_true", help="compare, do not write")
    args = parser.parse_args(argv)
    out: Path = args.out or args.root / GROUPS_FILE
    try:
        text = render_groups(load_dataset(DatasetPaths.under(args.root)))
    except DatasetError as error:
        print(f"the dataset is invalid: {error}", file=sys.stderr)
        return 1
    if not args.check:
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out}")
        return 0
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        print(f"{out} is stale; run `just blueprints` and commit it", file=sys.stderr)
        return 1
    print(f"{out} is up to date")
    return 0
